name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Greet the user
        run: |
          echo "Hello and welcome to the repository! Thank you for opening an issue or pull request. We will do our best to address it as soon as possible."
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "Thanks for opening your first issue in our repository! We appreciate your feedback and will do our best to address it as soon as possible."
          pr-message: "Thanks for opening your first pull request in our repository! We appreciate your contribution and will review it as soon as possible."
      - uses: actions/label@v2
        with:
            repo-token: ${{ secrets.GITHUB_TOKEN }}
            labels: 'good first issue'
