name: Label

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Get changed files
        run: |
          git diff --name-only HEAD@{1} HEAD > changed_files.txt
      - name: Label pull request
        run: |
          if grep -q "^server/" changed_files.txt; then
            echo "Labeling pull request with 'server'"
            curl -X POST -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -H "Content-Type: application/json" -d '{"labels": ["server"]}' "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.number }}/labels"
          elif grep -q "^client/" changed_files.txt; then
            echo "Labeling pull request with 'client'"
            curl -X POST -H "Authorization: Bearer ${{ secrets.GITHUB
